apiVersion: v1
kind: Pod
metadata:
  name: jaeger
  labels:
    infrastructure: jaeger
    app: delivery
spec:
  containers:
    - name: jaeger
      image: jaegertracing/all-in-one:1.44
      env:
        - name: COLLECTOR_OLTP_ENABLED
          value: "true"
      ports:
        - containerPort: 4317
          name: otlp
          protocol: TCP
        - containerPort: 16686
          name: ui
          protocol: TCP
