apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app: delivery
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 4317
      targetPort: 4317
    - protocol: TCP
      port: 16686
      targetPort: 16686
      # Optional field,
      nodePort: 30083
  selector:
    api: jaeger
