apiVersion: v1
kind: Pod
metadata:
  name: clients-microservice
  labels:
    api: client
    app: delivery
spec:
  containers:
    - name: client-mc
      image: jkakats/client-microservice:1.0.1
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
